// Get Input (Now we are using Input 8.0)
global.leftKey = input_check("left")
global.rightKey = input_check("right")
global.upKey = input_check("up")
global.downKey = input_check("down")
	
global.runKey = input_check("run")
global.shootKey = input_check("shoot")
global.swapGunKey = input_check_pressed("swap")
global.interact = input_check_pressed("action")